config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :users
  resources :dashboard do
	  collection do 
	  	get 'report' => 'dashboard#report',as: :report
	  end
  end

  root 'home#index'
  get 'energy' => 'home#energy'
  get 'water'  => 'home#water'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/farmer.rb
class Farmer < ApplicationRecord
  belongs_to :user
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
end

app/models/pump.rb
class Pump < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/soil_health.rb
class SoilHealth < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :role
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	layout 'dashboard'
	def index
	end

	def report
	end
end

app/controllers/home_controller.rb
require 'rss'
require 'open-uri'

class HomeController < ApplicationController
    def index
    end

    def energy
    	if File.exist?("public/bengaluru-power-news-cache.xml")
		begin
				File.open("public/bengaluru-power-news-cache.xml") do |rss|
					feed = RSS::Parser.parse(rss)
					@channel_title = feed.channel.title
					puts @channel_title.inspect
					@feed_items = feed.items
				end
		rescue
			@feed_items = []
		end
		end
    end
end

app/controllers/pump_controller.rb
class PumpController < ApplicationController
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
	def show
    	@role = Role.find(params[:id])
  	end

	def new
	end

	def create
		@role = Role.new(role_params)
		@role.save
		redirect_to @role
  	end

  	private
  		def role_params
    		params.require(:role).permit(:title, :description)
  		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def new
		@user = User.new
		@roles = Role.all
	end

	def create
		@user = User.new(user_params)

		if @user.save
			redirect_to users_path
		else
			@roles = Role.all
			render :action => 'new'
		end
	end

	def user_params
		params.require(:users).permit(:role_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/farmers_helper.rb
module FarmersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pump_helper.rb
module PumpHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/soil_health_helper.rb
module SoilHealthHelper
end

app/helpers/technicians_helper.rb
module TechniciansHelper
end

app/helpers/user_pump_helper.rb
module UserPumpHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/_sidebar_menu.html.erb
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
  <div class="menu_section">
    <ul class="nav side-menu">
      <li><%= link_to dashboard_index_path do %> <i class="fa fa-table"></i> Detail <% end %>
      </li>

      <li><%= link_to report_dashboard_index_path do %> <i class="fa fa-line-chart"></i> Reports <% end %>
      </li>

      <li><a><i class="fa fa-home"></i> Historical Reports </a>
      </li>

      <li><a><i class="fa fa-home"></i> Recent Activity </a>
      </li>

      <li><a><i class="fa fa-home"></i> Service </a>
      </li>

      <li><a><i class="fa fa-home"></i> Support </a>
      </li>

      <li><a><i class="fa fa-home"></i> Queries </a>
      </li>

    </ul>
  </div>
</div>